spring:
  application:
    name: config-server
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/optima-growth-stock/config
          default-label: main
          search-paths:
            - licensingservice
            - organizationservice
            - eurekaserver

# This value should be passed as environment variable, but for ease of usage it's defined here.
encrypt:
  key: INSYMETRIC

server:
  port: 8071
